### PR TITLE
added consul KV get support

### PR DESCRIPTION
**Pull request by grogsaxle**

### CODE REVIEW

**Comment by amanelis** [comment]
Very nice on the test 👍 just looks like it failed. Once fixed, merge @grogsaxle

**Comment by JohnDzialo** [comment]
Just curious why you are setting the value to '6666' before returning it?

**Comment by grogsaxle** [comment]
When the value returned from consul is None, it is throwing an exception with this implementation.  Does that seem reasonable?

**Comment by JohnDzialo** [comment]
Nope, I would verify if value is not None: return value, instead of if value, else logger that you got None from the kv call with the key you used

**Comment by JohnDzialo** [comment]
Looks good, you will want to remove service_name from the logger since it doesn't exist in the method

**Pull request merged**
