### PR TITLE
Consul get_service_url and get_service_ip_addresses

### PR DESCRIPTION
**Pull request by JohnDzialo**

### CODE REVIEW

**Comment by amanelis** [comment]
@JohnDzialo looks like you need to leave the dependency.

**Comment by JohnDzialo** [comment]
@amanelis what's weird is that it passes tests locally...

**Comment by JohnDzialo** [comment]
nevermind!!! it was make install && make test issue (ugg)

**Comment by amanelis** [comment]
we gotta solve this whole `make install` issue. nice @JohnDzialo

**Comment by amanelis** [comment]
👍

**Pull request merged**
